[stable]
features=["linux"]

[target.x86_64-unknown-linux-gnu]
linker = "clang"
rustflags = ["-C", "link-arg=-fuse-ld=mold"]

#[target.armv7-linux-androideabi]
#linker = "/home/CC/software/android/sdk/ndk/25.1.8937393/toolchains/llvm/prebuilt/linux-x86_64/bin/aarch64-linux-android30-clang"
#rustflags = ["-C", "link-arg=-fuse-ld=/home/CC/software/android/sdk/ndk/25.1.8937393/toolchains/llvm/prebuilt/linux-x86_64/bin/ld"]

