name: Rust

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

env:
  CARGO_TERM_COLOR: always

jobs:
  check-linux:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: Swatinem/rust-cache@v2
        with:
          key: ${{ runner.os }}-cargo-${{ hashFiles('**/Cargo.lock') }}
          cache-on-failure: true
          cache-directories: |
            ~/.cargo/registry
            ~/.cargo/git
            ./target
          prefix-key: ${{ runner.os }}-cargo-
      - name: Cache APT packages
        uses: actions/cache@v4
        with:
          path: /var/cache/apt/archives/*.deb
          key: ${{ runner.os }}-apt-mold-x11-dbus
          restore-keys: |
            ${{ runner.os }}-apt-
      - name: Install mold
        run: sudo apt-get install mold libx11-dev libdbus-1-dev libXft-dev -y

      - name: Check Native
        run: cargo check
      - name: Check WInit
        run: cargo check --features winit,gpu
      - name: Doc tests
        run: cargo test --doc --all
  check-windows:
    runs-on: windows-latest
    steps:
      - uses: actions/checkout@v4.0.0
      - uses: Swatinem/rust-cache@v2
        with:
          key: ${{ runner.os }}-cargo-${{ hashFiles('**/Cargo.lock') }}
          cache-on-failure: true
          cache-directories: |
            ~/.cargo/registry
            ~/.cargo/git
            ./target
          prefix-key: ${{ runner.os }}-cargo-
      - name: Check Native
        run: cargo check
      - name: Check WInit
        run: cargo check --features winit,gpu

